### ISSUE TITLE
Tiny Cloud error in Add Offer form 

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#112]
I keep seeing this error and i do not understand what is it related to

![image](https://user-images.githubusercontent.com/45068169/156621180-b8c2644c-0d47-4591-bcb9-0348dfe2c879.png)

**Comment by Cosmin-Parvulescu** [comment]
The text editor is called TinyCloud. It’s loaded in multiple places and uses an API KEY (which should be hidden behind env tbh). 

API key: `bgsado4b682dgf10owt5ns07i6jh5vcf36tc06nntxc08asr `

TinyCloud website: https://www.tiny.cloud/

It’s either you still have access to this account and can add the new domain under whitelists or you need a new account in order to generate a new API key.

I am not sure if it can be done without an API key. Might be worth investigating as I saw this kind of line in the documentation:
`<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>` - notice the **no-api-key**, though I doubt it.

**Comment by gheorghelupu17** [comment]
ma ocup eu de asta @Cosmin-Parvulescu
