### ISSUE TITLE
[Must Have] Add Upload ID field in Offer Housing form

### ISSUE THREAD

**Issue by overeha** [code4romania/war-support-un-acoperis#155]
People who offer housing must upload their ID in the platform as a picture. 
Add a Upload ID field in the form as the first field in the Offer Housing screen.

**Comment by gheorghelupu17** [comment]
E doar pentru persoane fizice sau persoanele juridice trebuie să încarce cui ?

**Comment by overeha** [comment]
good point i will check. dar either way we need an upload field

**Comment by stauciuc** [comment]
How will you verify the authenticity of the ID?
Human traffickers will likely have access to fake IDs. 

Also, how will you verify that the image is an identity document and not a cat photo? If there's no process for this, it may be too late by the time someone notices it.

Suggest requiring both id photo and self-portrait and implementing some sort of lazy verification process (e.g. crowdsourced to a small community of volunteers; I suppose AI-based takes too long to implement) for going through all profiles and verifying that the photos are in order and the ID information legible.
Ideally getting the police into the loop to run names through their databases.

Even so, the human trafficking risk will not be completely addressed, but it might just keep most of them away

**Comment by sandrohanea** [comment]
I think a scalable solution will be to have a card authorization (delegating identification to banks) instead of uploading an ID that cannot be easily verified. 

Again, the risk will not be completely addressed but it will be lower than uploading some documents even if those are manually checked by volunteers.

Unfortunately, this will introduce some reticency from people trying to offer help.

**Comment by overeha** [comment]
Just to reply to the comments above. The Department for Emergency Situations has a procedure to verify. There is no automatic verification for this. There are people who will check the ID and then also people on the ground visiting and inspecting the properties should it be the case before approving a housing offer. 

This is not an automatic check. The authorities will verify offline.

**Comment by mail4taz** [comment]
@overeha a couple of questions

1. does it make sense to be on the Offer Housing screen instead of the My Account section? How is this ID linked to the housing offer? If it's gonna be the ID of user who is responsible for the refugees during the stay, it would make sense to have 1 ID for all housing added in the platform by the same user. If we are expecting to be the ID of the house owner then yes, most likely we need to have 1 offer ~ 1 ID uploaded.

2. If the answer to prev question is 1 ID per 1 housing offer, can that ID by edited during the Edit housing offer screen?

3. what type of ID's will we be allowing. As far as I understand we won't run any automated validation checks, but there should be a minimal description, like "upload a photo of your CI or passport". So what type of documents can a user add - passport / driving license / CI?

Thanks
